const scriptSlideFolders = {
  cst_intro_reminiscence: 'session1',
  cst_childhood: 'session2',
  cst_physical_games: 'session3',
};

const adaptiveReminiscence = (guidance) => ({
  enabled: true,
  guidance,
});

const seatedExerciseInteraction = {
  type: 'youtubeShort',
  videoId: 'xVdKRNiAmqI',
  videoUrl: 'https://www.youtube.com/shorts/xVdKRNiAmqI',
  completionPrompt: 'When you are finished, press Done, or say or type "done" to continue.',
};

const spotifySongInteraction = ({ summarizeOnComplete = false } = {}) => ({
  type: 'spotifySong',
  playbackSeconds: 60,
  ...(summarizeOnComplete ? { summarizeOnComplete: true } : {}),
});

const physicalGamesWheelOptions = [
  { label: 'Favorite Sport', question: 'What is a favourite sport you enjoy watching or playing?' },
  { label: 'Sports Team', question: 'Is there a sports team you especially like?' },
  { label: 'Sporting Memory', question: 'What sporting moment do you remember especially well?' },
  { label: 'School Games', question: 'What games or sports did you enjoy at school?' },
  { label: 'Walking', question: 'Is there a place where you especially enjoy going for a walk?' },
  { label: 'Swimming', question: 'Do you have any memories of swimming or being near the water?' },
  { label: 'Dancing', question: 'What kind of dancing or dance music do you enjoy?' },
  { label: 'Rugby', question: 'Do you enjoy rugby, or remember a rugby match that stood out?' },
  { label: 'Olympics', question: 'Which Olympic sport do you most enjoy watching?' },
  { label: 'Team Games', question: 'Do you prefer team games or individual activities?' },
  { label: 'Indoor Games', question: 'What indoor physical game or activity do you enjoy?' },
  { label: 'Outdoor Games', question: 'What outdoor game or activity do you enjoy?' },
  { label: 'Staying Active', question: 'What is your favourite way to stay active?' },
  { label: 'Sports on TV', question: 'What sport do you most enjoy watching on television?' },
  { label: 'A Proud Moment', question: 'Is there a physical activity or sporting moment that made you feel proud?' },
  { label: 'Summer Sport', question: 'What sport or activity do you associate with summer?' },
  { label: 'Winter Sport', question: 'What sport or activity do you associate with winter?' },
  { label: 'Exercise Music', question: 'Is there music that makes you want to move or dance?' },
  { label: 'Try Something New', question: 'Is there a physical activity you would like to try?' },
  { label: 'Then and Now', question: 'How have the games or activities you enjoy changed over the years?' },
];

const scripts = {
  cst_intro_reminiscence: [
    {
      id: 'welcome_opening',
      turns: 1,
      acceptAnyAnswer: true,
      deckSlide: 1,
      title: 'AI-supported Individual Cognitive Stimulation Therapy',
      subtitle: 'Session 1: Introduction & Welcome',
      prompt: 'How are you feeling right now?',
      bullets: ['Introduction & Welcome', 'AI-supported CST', 'University of Auckland'],
      visualHint: 'Source deck: NZ01. Welcome, slide 1',
      accent: '#00AEEF',
      reply: ({ name }) =>
        `Hello ${name}, and welcome. I am Aria, and I will be guiding you through this AI-supported Cognitive Stimulation Therapy session. Today is our first session, so we will take it gently and get comfortable together. How are you feeling today? Is there anything you’d like to share about your day so far?`,
    },
    {
      id: 'facilitator_role',
      turns: 1,
      acceptAnyAnswer: true,
      deckSlide: 2,
      title: 'Your AI-supported CST Facilitator',
      subtitle: 'What I am here to do',
      prompt: 'Do you have a nickname or preferred name?',
      bullets: ['Keep each other company', 'Try interesting questions', 'Enjoy fun conversations'],
      visualHint: 'Source deck: NZ01. Welcome, slide 2',
      accent: '#F47C20',
      reply: ({ name }) =>
        `My role is to keep you company, try some interesting questions with you, and enjoy some fun conversation together. There are no tests here and no right or wrong answers. I know your name is ${name}, but do you have a nickname or another name you would prefer me to call you?`,
    },
    {
      id: 'introduce_yourself',
      turns: 3,
      acceptAnyAnswer: true,
      deckSlide: 3,
      title: 'Introduce Yourself',
      subtitle: 'Getting to know you',
      prompt: 'Where do you live?',
      bullets: ['Where you live', "Who's at home with you", 'Computer or tablet comfort'],
      visualHint: 'Source deck: NZ01. Welcome, slide 3',
      accent: '#F4C8B0',
      reply: () =>
        'Thank you. I would love to learn a little more about you. Where do you live?',
      followUps: [
        () => "And who is at home with you these days?",
        () => 'And how are you finding using your computer or tablet today?',
      ],
    },
    {
      id: 'what_is_cst',
      turns: 1,
      acceptAnyAnswer: true,
      deckSlide: 4,
      title: 'What is CST?',
      subtitle: 'Cognitive Stimulation Therapy',
      prompt: 'What do you think about that?',
      bullets: ['Evidence-based', 'Developed at University College London', 'Memory, mood, communication, and social engagement'],
      visualHint: 'Source deck: NZ01. Welcome, slide 4',
      accent: '#A8C5A0',
      reply: () =>
        'Cognitive Stimulation Therapy, or CST, is an evidence-based therapy for people living with cognitive changes or memory loss. It was developed at University College London, and it is designed to actively stimulate the mind in a supportive environment. What do you think about that?',
    },
    {
      id: 'cst_interests',
      turns: 1,
      acceptAnyAnswer: true,
      deckSlide: 5,
      title: 'What is CST?',
      subtitle: 'What you may be interested in',
      prompt: 'Which of those sounds most useful or enjoyable to you?',
      bullets: ['Improving memory and thinking', 'Being with others experiencing similar changes', 'Sharing thoughts and ideas', 'Having some fun'],
      visualHint: 'Source deck: NZ01. Welcome, slide 5',
      accent: '#F47C20',
      reply: () =>
        'People come to CST for different reasons. You may be interested in improving memory and thinking, being with others who understand similar changes, sharing thoughts and ideas, or simply having some fun. Which of those sounds most useful or enjoyable to you?',
    },
    {
      id: 'cst_nutshell',
      turns: 1,
      acceptAnyAnswer: true,
      deckSlide: 6,
      title: 'CST in a Nutshell',
      subtitle: 'The spirit of our sessions',
      prompt: 'Which of those ideas do you like best?',
      bullets: ['Mental stimulation', 'Opinions rather than facts', 'New ideas and associations'],
      visualHint: 'Source deck: NZ01. Welcome, slide 6',
      accent: '#F47C20',
      reply: () =>
        'In a nutshell, CST is about gentle mental stimulation, your opinions rather than facts, and exploring new ideas, thoughts, and associations. Which of those ideas do you like best?',
    },
    {
      id: 'session_themes',
      turns: 1,
      acceptAnyAnswer: true,
      deckSlide: 7,
      title: 'CST Session Themes',
      subtitle: 'What we will explore',
      prompt: 'Which theme sounds most interesting to you?',
      bullets: ['Welcome', 'Childhood', 'Physical games', 'Sounds', 'Food/Kai', 'Current affairs', 'Word games'],
      visualHint: 'Source deck: NZ01. Welcome, slide 7',
      accent: '#F47C20',
      reply: () =>
        'Across the sessions, we will explore a range of themes, including childhood, physical games, sounds, food and kai, current affairs, word association, being creative, orientation, money, number games, word games, and a team quiz. Which theme sounds most interesting to you?',
    },
    {
      id: 'next_session',
      turns: 1,
      acceptAnyAnswer: true,
      deckSlide: 8,
      title: 'The Theme of the Next Session',
      subtitle: 'Session 2: Getting To Know You (Childhood)',
      prompt: 'What part would you like to remember?',
      bullets: ['Session 2', 'Getting To Know You', 'Childhood'],
      visualHint: 'Source deck: NZ01. Welcome, slide 8',
      accent: '#4472C4',
      reply: ({ sessionSummary }) =>
        `This has been a lovely first session. Thank you for your company and for sharing your thoughts. ${sessionSummary || 'Today, we got to know a little about you and introduced what CST will be like.'} Next time, our theme will be Getting To Know You, with a focus on childhood. Before we finish, what is one part of today that you would like to remember?`,
      completionReply: () =>
        'It was great sharing thoughts and ideas with you, and I am looking forward to our next session on Getting To Know You, focusing on childhood.',
    },
  ],
  cst_childhood: [
    {
      id: 'childhood_welcome_back',
      turns: 1,
      deckSlide: 1,
      title: 'AI-supported Individual Cognitive Stimulation Therapy',
      subtitle: 'Session 2: Getting to Know You (Childhood)',
      prompt: 'Welcome back',
      bullets: ['Session 2', 'Getting to Know You', 'Childhood'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 1',
      accent: '#00AEEF',
      reply: ({ name }) =>
        `Welcome back, ${name}. It is lovely to see you again. Today our theme is getting to know you, especially memories from childhood. When you are ready, say "I'm ready" to begin.`,
    },
    {
      id: 'childhood_check_in',
      turns: 1,
      deckSlide: 2,
      title: 'Theme Song',
      subtitle: 'Check in',
      prompt: 'How are you doing today?',
      bullets: ['Theme song', 'Check in', 'How are you doing today?'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 2',
      accent: '#F47C20',
      reply: () =>
        'How are you doing today?',
    },
    {
      id: 'theme_song_choice',
      turns: 1,
      deckSlide: 3,
      title: 'Theme Song',
      subtitle: 'A song to begin and end with',
      prompt: 'Is there a song you like to sing or play?',
      bullets: ['Favourite song', 'Beginning of session', 'End of session'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 3',
      accent: '#F47C20',
      reply: () =>
        'Is there a song you like to sing or play at the beginning and at the end of each session? If you know the artist too, please tell me their name.',
    },
    {
      id: 'childhood_orientation_day',
      turns: 1,
      deckSlide: 4,
      title: 'What day of the week is it?',
      subtitle: 'Getting our bearings',
      prompt: 'What day of the week is it?',
      bullets: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 4',
      accent: '#7A9DAD',
      reply: () =>
        'Let us get our bearings together. Do you happen to know what day of the week it is?',
    },
    {
      id: 'childhood_orientation_month',
      turns: 1,
      deckSlide: 5,
      title: 'What month are we enjoying?',
      subtitle: 'Getting our bearings',
      prompt: 'What month are we enjoying?',
      bullets: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 5',
      accent: '#00AEEF',
      reply: () =>
        'And what month are we enjoying at the moment?',
    },
    {
      id: 'childhood_orientation_year',
      turns: 1,
      deckSlide: 6,
      title: 'What year is it?',
      subtitle: 'Getting our bearings',
      prompt: 'What year is it?',
      bullets: ['Year', 'Calendar', 'No pressure'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 6',
      accent: '#F4C8B0',
      reply: () =>
        'And do you happen to know what year it is?',
    },
    {
      id: 'childhood_orientation_season',
      turns: 1,
      deckSlide: 7,
      title: 'Which season are we enjoying?',
      subtitle: 'Getting our bearings',
      prompt: 'Which season are we enjoying?',
      bullets: ['Spring', 'Summer', 'Autumn', 'Winter'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 7',
      accent: '#A8C5A0',
      reply: () =>
        'Which season are you enjoying where you are?',
    },
    {
      id: 'childhood_weather',
      turns: 1,
      deckSlide: 8,
      title: 'The Weather Is...',
      subtitle: 'Outside today',
      prompt: 'What is the weather like?',
      bullets: ['Sunny', 'Cloudy', 'Windy', 'Rainy', 'Stormy', 'Hot or cold'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 8',
      accent: '#7A9DAD',
      reply: () =>
        'What is the weather like out your window today?',
    },
    {
      id: 'childhood_current_affairs',
      turns: 1,
      deckSlide: 9,
      title: 'Current Affairs',
      subtitle: 'Big or small news',
      prompt: 'Have you heard anything interesting lately?',
      bullets: ['Local news', 'Weather', 'Sport', 'Something pleasant'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 9',
      accent: '#00AEEF',
      interaction: {
        type: 'positiveNews',
      },
      reply: ({ currentAffairs }) =>
        currentAffairs?.status === 'available'
          ? `Here is a positive story from New Zealand: ${currentAffairs.article.title}. You can ask me to tell you more, or tell me what you think about it.`
          : 'I could not find a clearly positive New Zealand story just now. Have you heard anything pleasant or interesting lately?',
    },
    {
      id: 'childhood_exercise_follow_along',
      turns: 1,
      deckSlide: 10,
      title: 'Exercises',
      subtitle: 'Gentle follow along',
      prompt: 'Would you like to try a short seated exercise?',
      bullets: ['Sit safely on a chair', 'Press play when ready', 'Only do what feels comfortable'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 10',
      accent: '#4472C4',
      interaction: {
        ...seatedExerciseInteraction,
      },
      recordAnswer: false,
      reply: () =>
        'Next is a short seated exercise. Please sit comfortably and safely on a sturdy chair. The video will start after I finish speaking. If it does not, press play. Only do what feels comfortable. When you are finished, press Done, or say or type done.',
    },
    {
      id: 'childhood_birthplace',
      turns: 2,
      deckSlide: 11,
      title: 'Your Childhood',
      subtitle: 'Where it began',
      prompt: 'Where were you born?',
      bullets: ['Where you were born', 'Where you grew up'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 11',
      accent: '#F4C8B0',
      adaptiveFollowUp: adaptiveReminiscence(
        'After birthplace and where they grew up, invite one concrete place, sensory, community, or then-versus-now memory.'
      ),
      reply: () =>
        'Now let us wander back to childhood. Where were you born?',
      followUps: [
        () => 'And where did you grow up?',
      ],
    },
    {
      id: 'childhood_parents',
      turns: 1,
      deckSlide: 12,
      title: 'Your Childhood',
      subtitle: 'Family names',
      prompt: "What are your mother and father's names?",
      bullets: ['Mother', 'Father', 'Family memories'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 12',
      accent: '#7A9DAD',
      adaptiveFollowUp: adaptiveReminiscence(
        'If comfortable, invite one warm memory, characteristic, shared activity, or family tradition connected to a parent.'
      ),
      reply: () =>
        "What are your mother and father's names?",
    },
    {
      id: 'childhood_siblings',
      turns: 1,
      deckSlide: 13,
      title: 'Your Childhood',
      subtitle: 'Brothers and sisters',
      prompt: 'Do you have any brothers or sisters?',
      bullets: ['Brothers', 'Sisters', 'Names'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 13',
      accent: '#00AEEF',
      adaptiveFollowUp: adaptiveReminiscence(
        'Invite one shared activity, childhood memory, similarity, or difference involving their siblings without probing conflict.'
      ),
      reply: () =>
        'Do you have any brothers or sisters? What are their names?',
    },
    {
      id: 'childhood_school',
      turns: 2,
      deckSlide: 14,
      title: 'Your Childhood',
      subtitle: 'School days',
      prompt: 'Where did you go to school?',
      bullets: ['School', 'Favourite subject', 'School memories'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 14',
      accent: '#A8C5A0',
      adaptiveFollowUp: adaptiveReminiscence(
        'After school and favourite subject, invite one teacher, classroom memory, reason for the preference, or gentle then-versus-now comparison.'
      ),
      reply: () =>
        'Where did you go to school?',
      followUps: [
        () => 'What was your favourite subject at school?',
      ],
    },
    {
      id: 'childhood_first_job',
      turns: 1,
      deckSlide: 15,
      title: 'Your Childhood',
      subtitle: 'First work',
      prompt: 'My first job was...',
      bullets: ['First job', 'First chores', 'Early responsibility'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 15',
      accent: '#F4C8B0',
      adaptiveFollowUp: adaptiveReminiscence(
        'Invite one task, feeling, person, lesson, or comparison with how similar work is done today.'
      ),
      reply: () =>
        'Thinking back to when you were young, what was your first job, or one of the first jobs or chores you remember doing?',
    },
    {
      id: 'childhood_modern_family',
      turns: 1,
      deckSlide: 16,
      title: 'Modern Family',
      subtitle: 'Your opinion',
      prompt: 'Have you seen the television show Modern Family, or have you only heard of it? If you have seen it, what did you think of it? If not, is there another television comedy you remember enjoying?',
      bullets: ['Television comedy', 'Characters and stories', 'Your opinion'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 16',
      accent: '#7A9DAD',
      adaptiveFollowUp: adaptiveReminiscence(
        'Distinguish viewers from people who have only heard of the show. Only ask viewers about its characters, stories, or humour. For non-viewers, acknowledge that gently and optionally invite another television comedy they remember enjoying.'
      ),
      reply: () =>
        'There is a television comedy called Modern Family. Have you seen it, or have you only heard of it? If you have seen it, what did you think? If not, is there another television comedy you remember enjoying?',
    },
    {
      id: 'childhood_about_aria',
      turns: 1,
      deckSlide: 17,
      title: 'Getting to Know Us',
      subtitle: 'About Aria',
      prompt: 'What would you like to know about me?',
      bullets: ['AI-supported CST', 'Research project', 'University of Auckland'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 17',
      accent: '#00AEEF',
      reply: () =>
        'This is a nice moment for you to get to know me too. I am Aria, an AI-supported CST facilitator being developed as part of a research project at the University of Auckland to explore how technology can support warm, individual CST conversations. What would you like to know about me?',
    },
    {
      id: 'childhood_spin_question',
      turns: 2,
      deckSlide: 18,
      title: 'Question Wheel',
      subtitle: 'Spin',
      prompt: 'Spin the wheel',
      bullets: ['Favourite things', 'Places', 'Memories', 'Family', 'School'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 18',
      accent: '#A8C5A0',
      interaction: {
        type: 'questionWheel',
        options: [
          { label: 'Favorite Sports Team', question: 'Do you have a favourite sports team, or a sport you enjoy watching?' },
          { label: 'Favorite Sport', question: 'What is a favourite sport you enjoy watching or playing?' },
          { label: 'A proud moment', question: 'What is something you have done that made you feel proud?' },
          { label: 'Childhood games', question: 'What game did you especially enjoy playing as a child?' },
          { label: 'Beach, Mountain or Lake', question: 'Would you choose the beach, the mountains, or a lake?' },
          { label: 'Childhood treats', question: 'Was there a special treat you enjoyed as a child?' },
          { label: 'Morning or Night?', question: 'Are you more of a morning person or a night person?' },
          { label: 'What do you do to relax?', question: 'What do you like to do to relax?' },
          { label: 'Favorite Book?', question: 'Do you have a favourite book, or a book you remember enjoying?' },
          { label: 'Chocolate or Vanilla?', question: 'Would you choose chocolate or vanilla?' },
          { label: 'First Car?', question: 'Do you remember your first car, or a car you especially liked?' },
          { label: 'What motivates you?', question: 'What helps motivate you?' },
          { label: 'Best place visited?', question: 'What is one of the best places you have visited?' },
          { label: 'Who do you admire?', question: 'Who is someone you admire?' },
          { label: 'Favorite Movie', question: 'Do you have a favourite movie?' },
          { label: 'Favorite Food', question: 'What is one of your favourite foods?' },
          { label: 'Favorite Trip', question: 'Do you remember a favourite trip or holiday?' },
          { label: 'Favorite Celebration', question: 'What celebration or special occasion do you remember enjoying?' },
          { label: 'Favorite TV Show', question: 'Do you have a favourite TV show?' },
          { label: 'Childhood Toy', question: 'Was there a toy or treasured object you especially remember from childhood?' },
        ],
      },
      adaptiveFollowUp: adaptiveReminiscence(
        'Deepen the landed topic with one question about specifics, reasons, personal meaning, associated memories, or a past-versus-present comparison.'
      ),
      reply: () =>
        'Now we have a question wheel. Press spin the wheel, and I will ask the question it lands on.',
      followUps: [
        ({ wheelQuestion }) => wheelQuestion || 'What question did the wheel land on?',
      ],
    },
    {
      id: 'childhood_summary_song',
      turns: 2,
      deckSlide: 19,
      title: 'Finally',
      subtitle: 'Looking back over today',
      prompt: 'What have we done today?',
      bullets: ['Summarise today', 'Theme song'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 19',
      accent: '#F4C8B0',
      interaction: spotifySongInteraction({ summarizeOnComplete: true }),
      recordAnswer: false,
      reply: ({ themeSong }) =>
        themeSong?.status === 'available'
          ? `Before we look back over today, your song, ${themeSong.track.name} by ${themeSong.track.artistLabel}, is ready. It can play for up to one minute. When you have finished listening, press Done, or say or type done.`
          : 'Before we look back over today, I was not able to prepare the song this time. Press Done, or say or type done, when you are ready to continue.',
      followUps: [
        ({ sessionSummary }) =>
          `Now let us look back over what we have done today. ${sessionSummary || 'We shared a few moments from today together.'} What is one part of today that you would like to remember?`,
      ],
    },
    {
      id: 'childhood_closing',
      turns: 1,
      autoCompleteAfterNarration: true,
      deckSlide: 20,
      title: 'The Theme of the Next Session',
      subtitle: 'Session 3: Physical Games',
      prompt: 'See you next time',
      bullets: ['Thank you', 'Next session', 'Physical Games'],
      visualHint: 'Source deck: NZ02. Getting to Know You (Childhood), slide 20',
      accent: '#4472C4',
      recordAnswer: false,
      reply: ({ name }) =>
        `That brings us to the end of today's session, ${name}. Our next session will be Physical Games. Take good care, and I will look forward to seeing you next time.`,
    },
  ],
  cst_physical_games: [
    {
      id: 'physical_games_welcome',
      turns: 1,
      deckSlide: 1,
      title: 'AI-supported Individual Cognitive Stimulation Therapy',
      subtitle: 'Session 3: Physical Games',
      prompt: 'Welcome back',
      bullets: ['Session 3', 'Physical Games'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 1',
      accent: '#00AEEF',
      reply: ({ name }) =>
        `Welcome back, ${name}. It is lovely to see you again. Today is our third session, and our theme will be Physical Games. When you are ready, say "I'm ready" to begin.`,
    },
    {
      id: 'physical_games_opening_song',
      turns: 1,
      deckSlide: 2,
      title: 'Theme Song',
      subtitle: 'Our song from Session 2',
      prompt: 'Listen to your theme song',
      bullets: ['Theme song', 'Listen together'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 2',
      accent: '#F47C20',
      interaction: spotifySongInteraction(),
      recordAnswer: false,
      reply: ({ themeSong }) =>
        themeSong?.status === 'available'
          ? `Let us begin with the theme song you chose last time, ${themeSong.track.name} by ${themeSong.track.artistLabel}. It can play for up to one minute. When you have finished listening, press Done, or say or type done.`
          : 'I could not find a saved theme song from last time. Press Done, or say or type done, when you are ready to continue.',
    },
    {
      id: 'physical_games_check_in',
      turns: 1,
      deckSlide: 3,
      title: 'Check-in',
      subtitle: 'How are you doing today?',
      prompt: 'How are you doing today?',
      bullets: ['Take your time', 'Share as much as you like'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 3',
      accent: '#F47C20',
      reply: () => 'Before we begin, how are you doing today?',
    },
    {
      id: 'physical_games_orientation_day',
      turns: 1,
      deckSlide: 4,
      title: 'What day of the week is it?',
      subtitle: 'Getting our bearings',
      prompt: 'What day of the week is it?',
      bullets: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 4',
      accent: '#7A9DAD',
      reply: () => 'Let us get our bearings together. Do you happen to know what day of the week it is?',
    },
    {
      id: 'physical_games_orientation_month',
      turns: 1,
      deckSlide: 5,
      title: 'What month are we enjoying?',
      subtitle: 'Getting our bearings',
      prompt: 'What month are we enjoying?',
      bullets: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 5',
      accent: '#00AEEF',
      reply: () => 'And what month are we enjoying at the moment?',
    },
    {
      id: 'physical_games_orientation_year',
      turns: 1,
      deckSlide: 6,
      title: 'What year is it?',
      subtitle: 'Getting our bearings',
      prompt: 'What year is it?',
      bullets: ['Year', 'Calendar', 'No pressure'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 6',
      accent: '#F4C8B0',
      reply: () => 'And do you happen to know what year it is?',
    },
    {
      id: 'physical_games_orientation_season',
      turns: 1,
      deckSlide: 7,
      title: 'Which season are we enjoying?',
      subtitle: 'Getting our bearings',
      prompt: 'Which season are we enjoying?',
      bullets: ['Winter', 'Summer', 'Autumn', 'Spring'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 7',
      accent: '#A8C5A0',
      seasonBranches: {
        winter: 'physical_games_season_winter',
        summer: 'physical_games_season_summer',
        autumn: 'physical_games_season_autumn',
        spring: 'physical_games_season_spring',
      },
      reply: () => 'Which season are we enjoying here in New Zealand?',
    },
    {
      id: 'physical_games_season_winter',
      turns: 1,
      deckSlide: 8,
      title: 'Winter',
      subtitle: 'The season we are enjoying',
      prompt: 'Winter',
      bullets: ['Cool weather', 'Shorter days'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 8',
      accent: '#7A9DAD',
      interaction: { type: 'autoAdvance' },
      nextStepId: 'physical_games_weather',
      recordAnswer: false,
      reply: () => 'That is winter, with cooler weather and shorter days.',
    },
    {
      id: 'physical_games_season_summer',
      turns: 1,
      deckSlide: 9,
      title: 'Summer',
      subtitle: 'The season we are enjoying',
      prompt: 'Summer',
      bullets: ['Warm weather', 'Longer days'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 9',
      accent: '#F47C20',
      interaction: { type: 'autoAdvance' },
      nextStepId: 'physical_games_weather',
      recordAnswer: false,
      reply: () => 'That is summer, with warmer weather and longer days.',
    },
    {
      id: 'physical_games_season_autumn',
      turns: 1,
      deckSlide: 10,
      title: 'Autumn',
      subtitle: 'The season we are enjoying',
      prompt: 'Autumn',
      bullets: ['Changing leaves', 'Cooler days'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 10',
      accent: '#F4C8B0',
      interaction: { type: 'autoAdvance' },
      nextStepId: 'physical_games_weather',
      recordAnswer: false,
      reply: () => 'That is autumn, when the leaves change and the days begin to cool.',
    },
    {
      id: 'physical_games_season_spring',
      turns: 1,
      deckSlide: 11,
      title: 'Spring',
      subtitle: 'The season we are enjoying',
      prompt: 'Spring',
      bullets: ['New growth', 'Warmer days'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 11',
      accent: '#A8C5A0',
      interaction: { type: 'autoAdvance' },
      nextStepId: 'physical_games_weather',
      recordAnswer: false,
      reply: () => 'That is spring, with new growth and warmer days returning.',
    },
    {
      id: 'physical_games_weather',
      turns: 1,
      deckSlide: 12,
      title: 'The Weather Is...',
      subtitle: 'Outside today',
      prompt: 'What is the weather like?',
      bullets: ['Sunny', 'Cloudy', 'Windy', 'Rainy', 'Stormy', 'Hot or cold'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 12',
      accent: '#7A9DAD',
      reply: () => 'What is the weather like out your window today?',
    },
    {
      id: 'physical_games_current_affairs',
      turns: 1,
      deckSlide: 13,
      title: 'Current Affairs',
      subtitle: 'A different positive story',
      prompt: 'What do you think about that story?',
      bullets: ['New Zealand', 'Positive news', 'Ask for more'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 13',
      accent: '#00AEEF',
      interaction: { type: 'positiveNews' },
      reply: ({ currentAffairs }) =>
        currentAffairs?.status === 'available'
          ? `Here is a different positive story from New Zealand: ${currentAffairs.article.title}. You can ask me to tell you more, or tell me what you think about it.`
          : 'I could not find a new positive New Zealand story just now. Have you heard anything pleasant or interesting lately?',
    },
    {
      id: 'physical_games_exercise',
      turns: 1,
      deckSlide: 14,
      title: 'Exercises',
      subtitle: 'Gentle follow along',
      prompt: 'Try a short seated exercise',
      bullets: ['Sit safely', 'Only do what feels comfortable', 'Press Done when finished'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 14',
      accent: '#4472C4',
      interaction: { ...seatedExerciseInteraction },
      recordAnswer: false,
      reply: () =>
        'Next is the same short seated exercise. Please sit comfortably and safely on a sturdy chair. The video will start after I finish speaking. Only do what feels comfortable. When you are finished, press Done, or say or type done.',
    },
    {
      id: 'physical_games_theme_intro',
      turns: 1,
      deckSlide: 15,
      title: 'Physical Games',
      subtitle: 'Our theme for today',
      prompt: 'Physical Games',
      bullets: ['Sports', 'Activities', 'Movement'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 15',
      accent: '#F47C20',
      interaction: { type: 'autoAdvance' },
      recordAnswer: false,
      reply: () => 'Now it is time to move to our theme for today: Physical Games.',
    },
    {
      id: 'physical_games_favourite_sport',
      turns: 1,
      deckSlide: 16,
      title: 'Your Favourite Sport',
      subtitle: 'Playing and watching',
      prompt: 'What is your favourite sport?',
      bullets: ['Favourite sport', 'Sports you played'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 16',
      accent: '#A8C5A0',
      adaptiveFollowUp: adaptiveReminiscence(
        'Invite one gentle memory about playing, watching, a team, a person, or why the sport matters to them.'
      ),
      reply: () => 'What is your favourite sport? Did you play any sport yourself?',
    },
    {
      id: 'physical_games_non_competitive',
      turns: 1,
      deckSlide: 17,
      title: 'Physical Activities',
      subtitle: 'Without competition',
      prompt: 'Which non-competitive activity do you enjoy?',
      bullets: ['Walking', 'Gardening', 'Dancing', 'Swimming'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 17',
      accent: '#7A9DAD',
      adaptiveFollowUp: adaptiveReminiscence(
        'Invite one detail about where, when, with whom, or how the activity feels.'
      ),
      reply: () => 'What physical activities do you enjoy that do not require competition?',
    },
    {
      id: 'physical_games_staying_active',
      turns: 1,
      deckSlide: 18,
      title: 'Staying Active',
      subtitle: 'Moving in ways you enjoy',
      prompt: 'What is your favourite way to stay active?',
      bullets: ['Gentle movement', 'Everyday activity'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 18',
      accent: '#00AEEF',
      adaptiveFollowUp: adaptiveReminiscence(
        'Invite a comfortable example, routine, setting, or reason they enjoy this way of staying active.'
      ),
      reply: () => 'What is your favourite way to stay active?',
    },
    {
      id: 'physical_games_action_preview',
      turns: 1,
      deckSlide: 19,
      title: '3-2-1 Action!',
      subtitle: 'Movement ideas',
      prompt: 'Movement ideas',
      bullets: ['Swimming', 'Rugby', 'Dancing', 'Basketball', 'Yoga', 'Weight lifting'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 19',
      accent: '#F4C8B0',
      interaction: { type: 'autoAdvance' },
      recordAnswer: false,
      reply: () =>
        'Here are several ways people move, including swimming, rugby, dancing, basketball, yoga, and weight lifting. We will leave the action activity for another time and move gently to our word game.',
    },
    {
      id: 'physical_games_scattergories',
      turns: 1,
      deckSlide: 20,
      title: 'Physical Games Scattergories',
      subtitle: 'Sports beginning with one letter',
      prompt: 'Which sports or physical games begin with your letter?',
      bullets: ['Find a pen and paper', 'Choose a letter', 'Make a list', 'Tell Aria your words'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 20',
      accent: '#F4C8B0',
      reply: () =>
        'Do you have a pen and paper nearby? Choose a letter, or use the letter S if you would like a suggestion. Write down as many sports or physical games beginning with that letter as you can. When you are ready, tell me the words on your list. It is also fine to say, "I am not sure."',
    },
    {
      id: 'physical_games_olympic_intro',
      turns: 1,
      deckSlide: 21,
      title: 'Olympic Trivia',
      subtitle: 'A gentle quiz',
      prompt: 'Are you ready for Olympic trivia?',
      bullets: ['Take your time', 'Guess if you like', 'It is okay to be unsure'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 21',
      accent: '#4472C4',
      reply: () =>
        'It is time for some Olympic trivia. These are just for fun, and it is completely alright to guess or say, "I am not sure." When you are ready, say ready.',
    },
    {
      id: 'physical_games_trivia_next_olympics',
      turns: 1,
      deckSlide: 22,
      title: 'Olympic Trivia',
      subtitle: 'The next Summer Olympics',
      prompt: 'When and where are the next Summer Olympics?',
      bullets: ['Year', 'Host city'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 22',
      accent: '#00AEEF',
      acceptAnyAnswer: true,
      reply: () => 'When will the next Summer Olympics be held, and which city is hosting them?',
    },
    {
      id: 'physical_games_trivia_next_olympics_answer',
      turns: 1,
      deckSlide: 23,
      title: 'LA28',
      subtitle: 'Los Angeles 2028',
      prompt: 'Los Angeles 2028',
      bullets: ['Los Angeles', '2028 Summer Olympics'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 23',
      accent: '#F47C20',
      interaction: { type: 'autoAdvance' },
      recordAnswer: false,
      reply: () => 'The next Summer Olympics will be held in Los Angeles in 2028.',
    },
    {
      id: 'physical_games_trivia_uniform',
      turns: 1,
      deckSlide: 24,
      title: 'Olympic Trivia Question 1',
      subtitle: 'New Zealand uniform',
      prompt: 'Which colour is the New Zealand Olympic uniform usually based around?',
      bullets: ['New Zealand', 'Olympic uniform'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 24',
      accent: '#A8C5A0',
      acceptAnyAnswer: true,
      reply: () => 'What colour is the New Zealand Olympic team uniform usually based around?',
    },
    {
      id: 'physical_games_trivia_uniform_answer',
      turns: 1,
      deckSlide: 25,
      title: 'The Answer',
      subtitle: 'Black',
      prompt: 'Black',
      bullets: ['Black'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 25',
      accent: '#111111',
      interaction: { type: 'autoAdvance' },
      recordAnswer: false,
      reply: () => 'The answer is black.',
    },
    {
      id: 'physical_games_trivia_first_gold',
      turns: 1,
      deckSlide: 26,
      title: 'Olympic Trivia Question 2',
      subtitle: 'First individual gold',
      prompt: 'Who was the first New Zealander to win an individual Olympic gold medal?',
      bullets: ['New Zealand', 'Individual gold medal'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 26',
      accent: '#4472C4',
      acceptAnyAnswer: true,
      reply: () => 'Who was the first New Zealander to win an individual Olympic gold medal?',
    },
    {
      id: 'physical_games_trivia_first_gold_answer',
      turns: 1,
      deckSlide: 27,
      title: 'The Answer',
      subtitle: 'Ted Morgan',
      prompt: 'Ted Morgan',
      bullets: ['Welterweight boxing', 'Amsterdam 1928'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 27',
      accent: '#F4C8B0',
      interaction: { type: 'autoAdvance' },
      recordAnswer: false,
      reply: () =>
        'The answer is Ted Morgan, who won welterweight boxing gold at the 1928 Amsterdam Olympics. Jack Lovelock later won New Zealand’s first Olympic athletics gold in 1936.',
    },
    {
      id: 'physical_games_trivia_runner',
      turns: 1,
      deckSlide: 28,
      title: 'Olympic Trivia Question 3',
      subtitle: 'A famous New Zealand runner',
      prompt: 'Who won Olympic gold in 1960 and 1964?',
      bullets: ['800 metres', '1500 metres'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 28',
      accent: '#00AEEF',
      acceptAnyAnswer: true,
      reply: () =>
        'Which famous New Zealand athlete won Olympic gold in the 800 metres in 1960 and again in the 1500 metres in 1964?',
    },
    {
      id: 'physical_games_trivia_runner_answer',
      turns: 1,
      deckSlide: 29,
      title: 'The Answer',
      subtitle: 'Peter Snell',
      prompt: 'Peter Snell',
      bullets: ['Peter Snell'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 29',
      accent: '#A8C5A0',
      interaction: { type: 'autoAdvance' },
      recordAnswer: false,
      reply: () => 'The answer is Peter Snell.',
    },
    {
      id: 'physical_games_trivia_most_gold',
      turns: 1,
      deckSlide: 30,
      title: 'Olympic Trivia Question 4',
      subtitle: 'New Zealand gold medals',
      prompt: 'In which sport has New Zealand won the most Olympic gold medals?',
      bullets: ['New Zealand', 'Gold medals'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 30',
      accent: '#F47C20',
      acceptAnyAnswer: true,
      reply: () => 'In which sport has New Zealand won the most Olympic gold medals?',
    },
    {
      id: 'physical_games_trivia_most_gold_answer',
      turns: 1,
      deckSlide: 31,
      title: 'The Answer',
      subtitle: 'Rowing',
      prompt: 'Rowing',
      bullets: ['Rowing'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 31',
      accent: '#7A9DAD',
      interaction: { type: 'autoAdvance' },
      recordAnswer: false,
      reply: () => 'The answer is rowing.',
    },
    {
      id: 'physical_games_trivia_carrington',
      turns: 1,
      deckSlide: 32,
      title: 'Olympic Trivia Question 5',
      subtitle: 'Lisa Carrington',
      prompt: 'How many gold medals did Lisa Carrington win at Tokyo 2020?',
      bullets: ['Lisa Carrington', 'Tokyo 2020'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 32',
      accent: '#4472C4',
      acceptAnyAnswer: true,
      reply: () =>
        'Lisa Carrington became New Zealand’s most decorated Olympian at Tokyo 2020. How many gold medals did she win at those Games alone?',
    },
    {
      id: 'physical_games_trivia_carrington_answer',
      turns: 1,
      deckSlide: 33,
      title: 'The Answer',
      subtitle: 'Three gold medals',
      prompt: 'Three',
      bullets: ['Three gold medals'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 33',
      accent: '#F4C8B0',
      interaction: { type: 'autoAdvance' },
      recordAnswer: false,
      reply: () => 'The answer is three gold medals.',
    },
    {
      id: 'physical_games_spin_question',
      turns: 2,
      deckSlide: 34,
      title: 'Question Wheel',
      subtitle: 'Spin',
      prompt: 'Spin the wheel',
      bullets: ['Sports', 'Movement', 'Memories', 'Activities'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 34',
      accent: '#A8C5A0',
      interaction: {
        type: 'questionWheel',
        options: physicalGamesWheelOptions,
      },
      adaptiveFollowUp: adaptiveReminiscence(
        'Deepen the landed physical-games topic with one question about a memory, preference, reason, person, place, or then-versus-now comparison.'
      ),
      reply: () => 'Now we have the question wheel again. Press spin the wheel, and I will ask the question it lands on.',
      followUps: [
        ({ wheelQuestion }) => wheelQuestion || 'What question did the wheel land on?',
      ],
    },
    {
      id: 'physical_games_summary_song',
      turns: 2,
      deckSlide: 35,
      title: 'Finally',
      subtitle: 'Looking back over today',
      prompt: 'What have we done today?',
      bullets: ['Theme song', 'Summarise today'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 35',
      accent: '#F4C8B0',
      interaction: spotifySongInteraction({ summarizeOnComplete: true }),
      recordAnswer: false,
      reply: ({ themeSong }) =>
        themeSong?.status === 'available'
          ? `Before we look back over today, your theme song, ${themeSong.track.name} by ${themeSong.track.artistLabel}, is ready to play again. When you have finished listening, press Done, or say or type done.`
          : 'Before we look back over today, I was not able to prepare the theme song this time. Press Done, or say or type done, when you are ready to continue.',
      followUps: [
        ({ sessionSummary }) =>
          `Now let us look back over what we have done today. ${sessionSummary || 'Today, you explored physical games and activities together.'} What is one part of today that you would like to remember?`,
      ],
    },
    {
      id: 'physical_games_closing',
      turns: 1,
      deckSlide: 36,
      title: 'The Theme of the Next Session',
      subtitle: 'Session 4: Sounds',
      prompt: 'See you next time',
      bullets: ['Thank you', 'Next session', 'Sounds'],
      visualHint: 'Source deck: NZ03. Physical Games, slide 36',
      accent: '#4472C4',
      recordAnswer: false,
      reply: ({ name }) =>
        `That brings us to the end of today's session, ${name}. Our next session will explore Sounds. Take good care, and I will look forward to seeing you next time.`,
    },
  ],
};

export const getScript = (scriptId = 'cst_intro_reminiscence') =>
  scripts[scriptId] || scripts.cst_intro_reminiscence;

export const getScriptStepIndex = (scriptId, stepId) =>
  getScript(scriptId).findIndex((step) => step.id === stepId);

export const getScriptStep = (scriptId, stepIndex = 0) => {
  const script = getScript(scriptId);
  const boundedIndex = Math.min(Math.max(stepIndex, 0), script.length - 1);
  return {
    step: { slideFolder: scriptSlideFolders[scriptId] || 'session1', ...script[boundedIndex] },
    boundedIndex,
    isFinalStep: boundedIndex === script.length - 1,
    totalSteps: script.length,
  };
};

export const renderScriptReply = (step, context = {}) => {
  if (!step?.reply) return '';
  return typeof step.reply === 'function' ? step.reply(context) : String(step.reply);
};

export const renderScriptFollowUp = (step, followUpIndex, context = {}) => {
  const followUp = step?.followUps?.[followUpIndex];
  if (!followUp) return '';
  return typeof followUp === 'function' ? followUp(context) : String(followUp);
};
