// Shared steps are cloned from the previous session so media and branching stay aligned.
export function createFacesScenesScript(shared) {
  const clone = (suffix, deckSlide, overrides = {}) => {
    const source = shared.find((step) => step.id === `current_affairs_${suffix}`);
    const step = Object.defineProperties({}, Object.getOwnPropertyDescriptors(source));
    Object.assign(step, { id: `faces_scenes_${suffix}`, deckSlide, visualHint: `NZ07. Faces & Scenes, slide ${deckSlide}`, ...overrides });
    if (step.nextStepId) step.nextStepId = step.nextStepId.replace('current_affairs_', 'faces_scenes_');
    if (step.seasonBranches) step.seasonBranches = Object.fromEntries(Object.entries(step.seasonBranches).map(([season, id]) => [season, id.replace('current_affairs_', 'faces_scenes_')]));
    return step;
  };
  const discussion = (suffix, deckSlide, title, reply, details, clarification = '') => ({
    id: `faces_scenes_${suffix}`, deckSlide, title, subtitle: 'Faces and Scenes', prompt: title,
    turns: 1, acceptAnyAnswer: true, bullets: [], accent: '#4472C4',
    visualHint: `NZ07. Faces & Scenes, slide ${deckSlide}`,
    imageGuidance: { confirmedDetails: details, clarification },
    adaptiveFollowUp: { enabled: true, guidance: 'Accept plausible observations and personal opinions. Invite at most one related detail if they are interested; do not insist on a particular answer.' },
    reply: () => reply,
  });
  const matching = (suffix, deckSlide, title, descriptions, names, answers) => ({
    ...discussion(suffix, deckSlide, title,
      'Let us match each description to a famous person. Drag from a description to a name, or tap a description and then tap a name. The selected description will be highlighted. You can change a match, tell me your ideas, or press Done matching when you are ready.',
      descriptions.map((description, index) => `${description}: ${names[answers[index]]}`),
      'Use these associations to respond gently to matches. Never demand a perfect score. The original NZ slide omitted Michael Jones; he is included in this activity.'),
    adaptiveFollowUp: undefined,
    inactivityTimeoutMs: 180000,
    interaction: { type: 'matching', left: descriptions.map((label, index) => ({ id: `clue-${index}`, label })), right: names.map((label, index) => ({ id: `name-${index}`, label })) },
  });
  const celebrities = ['Billy T James: New Zealand comedian and entertainer', 'Dame Kiri Te Kanawa: New Zealand operatic soprano', 'Elvis Presley: American singer and actor', 'all three are well-known entertainers who performed on stage', 'two are from New Zealand', 'all three have sung'];
  const quiz = (slide, answer) => [
    {
      ...discussion(`real_ai_${slide}`, slide, 'Real or artificial intelligence?',
        'Do you think this is a photograph of a real person, or a face generated by AI? Choose Real person or AI generated, or tell me your guess. It is fine to be unsure.',
        ['a portrait of a person'], 'Do not reveal the supplied answer until the following answer slide. Appearance alone does not prove whether a face is real or generated.'),
      adaptiveFollowUp: undefined,
      interaction: { type: 'realOrAi' },
    },
    {
      id: `faces_scenes_real_ai_${slide}_reveal`, deckSlide: slide + 1,
      title: answer === 'real' ? 'Real person' : 'AI generated', subtitle: 'The answer from the deck',
      prompt: 'Let us see the answer', bullets: [], turns: 1,
      interaction: { type: 'autoAdvance' }, isAnswerReveal: true, recordAnswer: false,
      reply: () => `The deck labels this picture as ${answer === 'real' ? 'a real person' : 'AI generated'}. It can be difficult to tell from a picture alone. Thank you for having a go.`,
    },
  ];
  return [
    clone('welcome', 1, { subtitle: 'Session 7: Faces and Scenes', bullets: ['Session 7', 'Faces and Scenes'], reply: ({ name }) => `Welcome back, ${name}. Today is our seventh session: Faces and Scenes. We will look at familiar faces, compare places, and try a few picture activities together. Take your time. Say ready when you would like to begin.` }),
    clone('opening_song', 2), clone('check_in', 2),
    clone('orientation_day', 3), clone('orientation_month', 4), clone('orientation_year', 5), clone('orientation_year_reveal', 6), clone('orientation_season', 7),
    clone('season_winter', 8), clone('season_summer', 9), clone('season_autumn', 10), clone('season_spring', 11), clone('weather', 12),
    clone('positive_news', 13), clone('exercise', 14),
    clone('theme_intro', 15, { title: 'Faces and Scenes', prompt: 'Faces and Scenes', bullets: ['Faces', 'Places', 'Your ideas'], reply: () => 'Our theme today is Faces and Scenes. We will start with some familiar names, then explore photographs together.' }),
    matching('match_nz', 16, 'Match the description to the famous New Zealander', [
      'Climbed Mount Everest with Tenzing Norgay in 1953', 'Directed The Lord of the Rings films', 'All Black flanker nicknamed the Iceman', 'Played rugby league and union, and was a heavyweight boxer', 'Olympic gold medallist in shot put', 'Legendary All Black often called one of New Zealand’s greatest rugby players',
    ], ['Sonny Bill Williams', 'Edmund Hillary', 'Colin Meads', 'Peter Jackson', 'Valerie Adams', 'Michael Jones'], [1, 3, 5, 0, 4, 2]),
    matching('match_international', 17, 'Match the description to the famous international person', [
      'Known as the King of Rock and Roll', 'Hollywood actress in Some Like It Hot', 'Late Queen of the United Kingdom who reigned for over 70 years', 'Catholic nun known for charitable work with poor people in India', 'British Prime Minister during World War II, remembered for his speeches',
    ], ['Queen Elizabeth II', 'Elvis Presley', 'Winston Churchill', 'Marilyn Monroe', 'Mother Teresa'], [1, 3, 0, 4, 2]),
    discussion('celebrities_similar', 18, 'What is similar about these three people?', 'These pictures show Billy T James, Dame Kiri Te Kanawa, and Elvis Presley. What do you think they have in common?', celebrities,
      'Accept entertainers, singers, famous people, stage performers, or that two are New Zealanders. They do not all have the same nationality. Other visible similarities are welcome.'),
    discussion('celebrities_different', 19, 'What is different about these three people?', 'What differences do you notice between Billy T James, Dame Kiri Te Kanawa, and Elvis Presley?', celebrities,
      'Possible answers include comedy versus opera versus popular music, New Zealand versus America, clothes, hairstyle, or gender. Accept a reasonable answer without listing every difference.'),
    discussion('people_similar', 20, 'What is similar?', 'Look at these four people. What similarities do you notice?', ['four people', 'different hairstyles', 'casual or smart clothing'], 'Discuss visible similarities. Do not infer identity, health, personality, sexuality, or other private attributes from appearance.'),
    discussion('people_different', 21, 'What is different?', 'And what differences do you notice in their hair, clothes, or the way they are standing?', ['blue hair', 'red hair', 'dark hair', 'glasses', 'a jacket and tie', 'different clothes'], 'These are pictures of people. Accept observable differences without stereotypes or guessing private attributes.'),
    discussion('scene_preference', 22, 'Which scene do you prefer, and why?', 'Which of these two scenes would you prefer to visit, and what appeals to you about it?', ['mountains', 'snow', 'water in the left scene', 'a large building in the right scene'], 'Do not require the person to identify the locations. Preferences have no wrong answer.'),
    discussion('landmarks', 23, 'What is similar or different?', 'What similarities or differences do you notice between these two landmarks?', ['Eiffel Tower in Paris', 'Elizabeth Tower, often called Big Ben, in London', 'both are tall and well-known landmarks', 'a clock on the London tower'], 'Accept towers, cities, architecture, travel memories, or visible details. Do not insist on naming either landmark.'),
    {
      ...discussion('queen_street', 24, 'How has this place changed?', 'These two pictures show Queen Street in Auckland, one long ago and one more recently. What changes do you notice?', ['Queen Street in Auckland, New Zealand', 'an older black-and-white photograph', 'a more recent colour photograph', 'trams in the historic photograph', 'changes in traffic, buildings, trees, and pedestrian space'], 'The exact year of the historic photograph is unverified. Do not guess a year.'),
      turns: 2, adaptiveFollowUp: undefined,
      followUps: [({ previousAnswer = '' }) => /\btram(?:s|ways?)?\b/i.test(previousAnswer)
        ? 'You noticed the trams in the older picture. What do you remember about visiting a busy shopping street?'
        : 'Queen Street had a tram system in those earlier days, as we can see in the old photograph. What do you remember about visiting a busy shopping street?'],
    },
    ...quiz(25, 'real'), ...quiz(27, 'real'), ...quiz(29, 'ai'),
    clone('spin_question', 31),
    clone('summary_song', 32, { followUps: [({ sessionSummary }) => `Let us look back over today. ${sessionSummary || 'We matched famous people, compared faces and scenes, looked at Queen Street, and tried real-or-AI pictures.'} What is one part you would like to remember?`] }),
    clone('closing', 33, { subtitle: 'Session 8: Word Association', bullets: ['Thank you', 'Word Association'], reply: ({ name }) => `Thank you for joining me today, ${name}. Next time our theme is Word Association. Ka kite anō, and I look forward to seeing you again.` }),
  ];
}
